# Generated by Django 5.0 on 2023-12-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
